# Etapa 1: Build
FROM node:20-bullseye AS builder

WORKDIR /app

# Copia apenas os arquivos de dependência
COPY package*.json ./
COPY tsconfig*.json ./
COPY .env .env

# Instala dependências
RUN npm install

# Copia o restante do projeto
COPY . .

# Builda o projeto Nest
RUN npm run build

# Etapa 2: Produção
FROM node:20-bullseye AS production

WORKDIR /app

# Copia o necessário da etapa de build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/.env .env

# Define variáveis de ambiente
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

EXPOSE 3000

CMD ["node", "dist/main"]
